[workspace]
members = [
    "libs/jui_file"
]

[package]
name = "jui"
version = "0.1.2"
edition = "2021"
description = "jui is a ui set based on slint"
readme = "Readme.md"
authors = ["The jui developers"]
license = "MIT/Apache-2.0"
keywords = ["gui", "slint"]
categories = ["gui"]
repository = "https://github.com/lifeRobot/jui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbsk_base = { version = "0.1.5", features = ["once_cell"] }
cbsk_mut_data = { version = "0.1.3", features = ["obj"] }
slint-build = "1.3.2"
jui_file = "0.1.1"

[build-dependencies]
cbsk_base = { version = "0.1.5", features = ["once_cell"] }
cbsk_mut_data = { version = "0.1.3", features = ["obj"] }
jui_file = "0.1.1"
