[workspace]
members = [
    "libs/jui_file"
]

[package]
name = "jui"
version = "0.1.24"
edition = "2021"
description = "jui is a ui set based on slint"
readme = "Readme.md"
authors = ["The jui developers"]
license = "MIT/Apache-2.0"
keywords = ["gui", "slint"]
categories = ["gui"]
repository = "https://github.com/lifeRobot/jui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint-build = "1.5.1"
jui_file = "0.1.24"
#jui_file = { path = "./libs/jui_file" }

cbsk_base = { version = "1.2.0", optional = true }
reqwest = { version = "0.12.2", features = ["blocking"], optional = true }
zip = { version = "1.2.3", default-features = false, features = ["deflate"], optional = true }

[features]
# support SurrealismUI, you can use @surrealism import
surrealism_ui = ["reqwest", "cbsk_base/anyhow", "zip"]