component EmptyInit { }

export component Collapsible inherits Rectangle {
    in-out property <bool> show: true;
    private property <length> logic_height;

    animate height {
        duration: 500ms;
    }

    public function toggle() -> bool{
        show = !show;
        root.height = show ? logic_height : 0;
        return show;
    }

    EmptyInit {
        init => {
            root.logic_height = root.height;
            root.height = show ? logic_height : 0;
        }
    }

    @children
}