import { DrawerLeft } from "../drawer/drawer_left.slint";
import { DateTime,DateTimeData,ChooseNames,FunctionButtonName } from "./datetime.slint";

export { DateTimeData,ChooseNames,FunctionButtonName }

export component DateTimeRight inherits DrawerLeft {
    in-out property <DateTimeData> date_time <=> dt.date_time;
    in property <ChooseNames> choose_name <=> dt.choose_name;
    in property <string> time_name <=> dt.time_name;
    in property <FunctionButtonName> buttons <=> dt.buttons;
    callback ok <=> dt.ok;
    callback now <=> dt.now;
    callback cancel <=> dt.cancel;
    width: dt.width;
    height: dt.height;
    dt := DateTime { }

    public function get_date_time_str(time: DateTimeData) -> string {
        dt.get_date_time_str(time)
    }
}
