import { Date,Time } from "std-widgets.slint";
import { DateTimeData,ShowController,ChooseNames } from "./datetime_data.slint";
import { YearPickers } from "./year_pickers.slint";
import { MonthPickers } from "month_pickers.slint";
import { ChooseController } from "choose_controller.slint";
import { TimePickers,TimeData } from "./time_pickers.slint";
import { FunctionButton,FunctionButtonName } from "./function_button.slint";

export { DateTimeData,ChooseNames,FunctionButtonName }

component Footer inherits HorizontalLayout {
    height: 25px;
    in property <TimeData> data <=> time.data;
    in property <string> time_name <=> time.name;
    in property <bool> hour_active <=> time.hour_active;
    in property <bool> minute_active <=> time.minute_active;
    in property <bool> second_active <=> time.second_active;
    in property <FunctionButtonName> buttons <=> btn.buttons;
    callback ok <=> btn.ok;
    callback now <=> btn.now;
    callback cancel <=> btn.cancel;
    callback hour_clicked <=> time.hour_clicked;
    callback minute_clicked <=> time.minute_clicked;
    callback second_clicked <=> time.second_clicked;

    time := TimePickers { }

    btn := FunctionButton { }
}

export component DateTime inherits Rectangle {
    // set default
    in-out property <DateTimeData> date_time <=> body.data;
    in property <ChooseNames> choose_name <=> body.choose_name;
    in property <string> time_name <=> footer.time_name;
    in property <FunctionButtonName> buttons <=> footer.buttons;
    callback ok(DateTimeData, string);
    callback now() -> DateTimeData;
    callback cancel();
    // default now
    now => {
        { date:{ year:2024, month:9, day:1 } }
    }
    width: month_pick.x + month_pick.width + 10px;
    height: footer.y + footer.height + 10px;
    background: white;
    border-width: 1px;
    border-color: gray;

    year_pick := YearPickers {
        x: 10px;
        y: 10px;
        num: date_time.date.year;
        change(num) => {
            date_time.date.year = num;
        }
        clicked => {
            body.show_cont = ShowController.Year
        }
    }

    month_pick := MonthPickers {
        x: year_pick.x + year_pick.width + 30px;
        y: year_pick.y;
        num: date_time.date.month;
        min_back() => {
            date_time.date.year -= 1;
            date_time.date.month = self.max_limit.num;
        }
        max_next() => {
            date_time.date.year += 1;
            date_time.date.month = self.min_limit.num;
        }
        change(num) => {
            date_time.date.month = num;
        }
        clicked => {
            body.show_cont = ShowController.Month;
        }
    }

    body := ChooseController {
        width: month_pick.x + month_pick.width - year_pick.x;
        x: year_pick.x;
        y: month_pick.height + month_pick.y + 5px;
        start_week: get_start_week();
        max_day: get_month_last_day();
    }

    footer := Footer {
        width: body.width;
        x: body.x;
        y: body.y + body.height + 5px;
        hour_active: body.show_cont == ShowController.Hour;
        minute_active: body.show_cont == ShowController.Minute;
        second_active: body.show_cont == ShowController.Second;
        data: {
            hour:{ num:date_time.time.hour, str:get_time_str(date_time.time.hour) },
            minute:{ num:date_time.time.minute, str:get_time_str(date_time.time.minute) },
            second:{ num:date_time.time.second, str:get_time_str(date_time.time.second) },
        };
        hour_clicked => {
            body.show_cont = ShowController.Hour;
        }
        minute_clicked => {
            body.show_cont = ShowController.Minute;
        }
        second_clicked => {
            body.show_cont = ShowController.Second;
        }
        ok => {
            ok(date_time,@tr("{}-{}-{} {}:{}:{}",date_time.date.year,get_time_str(date_time.date.month),get_time_str(date_time.date.day),get_time_str(date_time.time.hour),get_time_str(date_time.time.minute),get_time_str(date_time.time.second)));
        }
        now => {
            date_time = now();
        }
        cancel => {
            cancel();
        }
    }

    // get time str, ensure that two digits are displayed
    function get_time_str(time: int) -> string {
        if time > 9 {
            return time;
        }
        @tr("0{}",time)
    }
    // get month days
    function get_month_last_day() -> int {
        if is_31(date_time.date.month) {
            return 31;
        }
        if is_30(date_time.date.month) {
            return 30;
        }
        if is_leap_year(date_time.date.year) {
            return 29;
        }
        28
    }
    // the month last day is 31
    function is_31(month: int) -> bool {
        month == 1 || month == 3 || month == 5 || month == 7 || month == 8 || month == 10 || month == 12
    }
    // the month last day is 30
    function is_30(month: int) -> bool {
        month == 4 || month == 6 || month == 9 || month == 11
    }
    // the year is leap year
    function is_leap_year(year: int) -> bool {
        if Math.mod(year,100) == 0 {
            return Math.mod(year,400) == 0;
        }
        Math.mod(year,4) == 0
    }
    // get month start week
    function get_start_week() -> int {
        get_week({ year:date_time.date.year, month:date_time.date.month, day:1 })
    }
    // get week, use Kim Larsen
    function get_week(date: Date) -> int {
        if date.month >= 3 {
            return get_week_base(date);
        }
        get_week_base({ year:date.year - 1, month:date.month + 12, day:date.day })
    }
    function get_week_base(date: Date) -> int {
        Math.mod((date.day + 2 * date.month + Math.floor(3 * (date.month + 1) / 5) + date.year + Math.floor(date.year / 4) - Math.floor(date.year / 100) + Math.floor(date.year / 400) + 1),7)
    }
}
