import { Button } from "../button/button.slint";

export struct FunctionButtonName {
    ok:string,
    now:string,
    cancel:string,
}

component FunctionButtonBase inherits Button {
    height: 25px;
    border_radius: 0;
    padding_width: 10px;
    plain: true;
    color: #80808080;
    hover_color: #80808060;
}

export component FunctionButton inherits HorizontalLayout {
    in property <FunctionButtonName> buttons:{ ok:"Ok", now:"Now", cancel:"Cancel" };
    callback ok();
    callback now();
    callback cancel();
    FunctionButtonBase {
        text: buttons.cancel;
        clicked => {
            cancel()
        }
    }

    FunctionButtonBase {
        text: buttons.now;
        clicked => {
            now()
        }
    }

    FunctionButtonBase {
        text: buttons.ok;
        clicked => {
            ok();
        }
    }
}
