import { ButtonLeft } from "../button/button_left.slint";
import { ButtonRight } from "../button/button_right.slint";
import { Button } from "../button/button.slint";

/// number limit
export struct NumberLimit {
    enable:bool,
    num:int,
}

export component NumberPickers inherits Rectangle {
    in property <NumberLimit> min_limit;
    in property <NumberLimit> max_limit;
    in-out property <int> num:0;
    width: left.width + cont.width + right.width;
    height: 25px;
    callback change(int);
    callback min_back(int);
    callback max_next(int);
    callback clicked <=> cont.clicked;
    left := ButtonLeft {
        x: 0;
        y: 0;
        width: root.height;
        clicked => {
            if min_limit.enable && min_limit.num >= num {
                min_back(num);
                return;
            }
            change(num - 1)
        }
    }

    cont := Button {
        x: root.height;
        hover_color: #00000050;
        width: 50px;
        border_radius: 0;
        border_width: 0;
        height: root.height;
        text: num;
    }

    right := ButtonRight {
        x: root.height + 50px;
        y: 0;
        width: root.height;
        clicked => {
            if max_limit.enable && max_limit.num <= num {
                max_next(num);
                return;
            }
            change(num + 1)
        }
    }
}
