import { Button } from "./button.slint";

export component ButtonRound inherits Button {
    in property <bool> active;
    in property <brush> active_color:#80808085;
    height: self.width;
    border_radius: self.height;
    border_width: 0;
    hover_color: #80808080;
    states [
        hover_focus when root.has_hover || root.has_focus || active: {
            plain: true;
            color: active_color;
        }
    ]
}
