import { TouchSpaceEnter } from "../event/touch_space_enter.slint";
import { ButtonOptBase } from "button_opt_base.slint";

export component ButtonOpt inherits ButtonOptBase {
    in property <bool> click_change_checked: true;
    logic_color: root.enabled && (root.checked || touch.has_hover || touch.has_focus) ? root.hover_color : root.color;

    callback clicked;

    states [
        is-loading when root.loading: {
            touch.space_enter_enabled: false;
        }
        disabled when !root.enabled: {
            touch.space_enter_enabled: false;
        }
    ]

    // support toggled and mouse cursor
    touch := TouchSpaceEnter {
        mouse-cursor: root.mouse_cursor;

        clicked => {
            if root.enabled {
                if click_change_checked {
                    root.checked = !root.checked;
                }
                root.clicked();
            }
        }
    }
}
