export component DrawerCommon {
    in-out property <bool> show: false;
    in property <brush> background: white;
    in-out property <duration> animation_animation:300ms;

    callback clicked <=> touch.clicked;

    x: 0;
    y: 0;
    width: 50%;
    height: 50%;

    animate width, height, x, y { duration: animation_animation; }


    // fix that triggers the click effect of covered layer components
    touch := TouchArea { }

    @children
}
