import { DrawerCommon } from "drawer_common.slint";

// drawer by top
export component DrawerTop inherits DrawerCommon {
    private property <length> logic_height;
    width: 100%;

    cont := Rectangle {
        background: root.background;
        clip: true;

        animate height { duration: 300ms; }

        init => {
            re_init(root.width,root.height);
        }

        @children
    }

    // the UI may delay initialization, causing the width to be 0 or less.
    // you can call this method again to reinitialize the drawer component after the UI is rendered
    public function re_init(w: length, h: length) {
        root.width = w;
        root.height = h;
        logic_height = h;
        change_height();
    }

    public function open() {
        change_show(true);
    }

    public function close() {
        change_show(false);
    }

    public function toggle() {
        change_show(!root.show);
    }

    public function change_show(show: bool) {
        root.show = show;
        change_height();
    }

    function change_height() {
        if root.show {
            root.height = logic_height;
            cont.height = logic_height;
            return;
        }
        root.height = 0;
        cont.height = 0;
    }
}
