import { DrawerCommon } from "drawer_common.slint";

// drawer by right
export component DrawerRight inherits DrawerCommon {
    private property <length> logic_width;
    private property <length> logic_x;
    height: 100%;

    cont:= Rectangle {
        background: root.background;
        clip: true;

        animate width {
             duration: 300ms;
        }

        init => {
            logic_width = root.width;
            logic_x = root.x;
            change_width();
        }

        @children
    }

    // open drawer
    public function open() {
        change_show(true);
    }

    // close drawer
    public function close() {
        change_show(false);
    }

    // toggle drawer
    public function toggle() {
        change_show(!root.show);
    }

    // open or close drawer
    public function change_show(show:bool) {
        root.show = show;
        change_width();
    }

    // change width, will open or close drawer
    function change_width() {
        if root.show {
            root.width = logic_width;
            cont.width = logic_width;
            root.x = logic_x;
            return;
        }

        root.width = 0;
        cont.width = 0;
        root.x = logic_x + logic_width;
    }
}